
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-backend
  namespace: atm2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-backend
  template:
    metadata:
      labels:
        app: django-backend
    spec:
      imagePullSecrets:
        - name: docker-registry-creds
      containers:
        - name: django
          image: raviarumugam001/django-atm:V1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8003
          envFrom:
            - configMapRef:
                name: django-config
            - secretRef:
                name: mysql-secret
          command:
            - sh
            - -c
            - |
              python wmanage.py migrate --noinput &&
              python wmanage.py runserver 0.0.0.0:8003
