apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: ecommerce-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
        ports:
          - containerPort: 9200
        env:
          - name: discovery.type
            value: single-node

          # 🔥 VERY IMPORTANT JVM SETTINGS
          - name: ES_JAVA_OPTS
            value: "-Xms512m -Xmx512m"

          - name: xpack.security.enabled
            value: "true"

          - name: ELASTIC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ecommerce-secrets
                key: ELASTIC_PASSWORD

        # 🧠 MEMORY LIMITS (MANDATORY)
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "1.5Gi"
            cpu: "1"

        # Prevent mmap crash in containers
        volumeMounts:
          - name: es-data
            mountPath: /usr/share/elasticsearch/data

      volumes:
        - name: es-data
          emptyDir: {}
