apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-backend
  namespace: ecommerce-prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ecommerce-backend
  template:
    metadata:
      labels:
        app: ecommerce-backend
    spec:
      imagePullSecrets:
        - name: docker-registry-creds
      containers:
      - name: flask
        image: raviarumugam001/ecommerce-backend:latest
        ports:
          - containerPort: 5000
        envFrom:
          - configMapRef:
              name: ecommerce-config
          - secretRef:
              name: ecommerce-secrets
        command:
          [ "sh", "-c", "./wait-for-it.sh postgres:5432 -- flask db upgrade && gunicorn -k eventlet -w 1 -b 0.0.0.0:5000 main:app" ]
