apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce-prod
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
  ELASTIC_PASSWORD: 7gqmr5DDb6KBA*XeMqiq
  NEO4J_AUTH: neo4j/BinRoot@123
  MONGO_ROOT_PASSWORD: abcd
  JWT_SECRET_KEY: QAWSEDRFTGYHUJ
  APP_SECRET_KEY: ECOMMERCE_MOST_SECURE_AUTH_1234
