apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: django-ingress
  namespace: atm
spec:
  ingressClassName: nginx
  rules:
  - host: onewebres.app.techg.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: django-backend
            port:
              number: 8003
