apiVersion: v1
kind: Service
metadata:
  name: django-atm-svc
  namespace: atm-prod
spec:
  type: ClusterIP
  selector:
    app: django-backend     # ✅ MATCHES POD LABELS
  ports:
  - name: http
    port: 80               # ✅ SERVICE PORT (Ingress uses this)
    targetPort: 8003       # ✅ CONTAINER PORT
