
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atm-django
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/RaviArumugam001/ATM-BE-F1.0.git
    targetRevision: master
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: atm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
