apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atm-django
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/RaviArumugam001/atm-gitops.git
    targetRevision: main
    path: atm-gitops-v1.0
  destination:
    server: https://kubernetes.default.svc
    namespace: atm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
